### PR TITLE
Added .gitkeep to \app\lib

### PR DESCRIPTION
**Pull request by kobus1998**
A temporary placeholder. When you don't have the folder lib you get a error when serving the site.
```
[RuntimeException]
Could not scan for classes inside "app/Lib/" which does not appear to be a file nor a folder
```

### CODE REVIEW

**Comment by kobus1998** [comment]
Seems like travis failed because of the same error I had
travis-fail

**Comment by svenluijten** [comment]
👍 

Somewhat related; @Feddman why do we load files in `app/Lib` via classmap though? They're included in the PSR-4 autoloaded block ([here](https://github.com/Radiuscollege/knb/blob/master/composer.json#L31)) under the `App\` namespace.

So you just have to give the classes in the `Lib` folder the namespace `App\Lib` for it to work:

```php
<?php

namespace App\Lib;

class Some
{
    //
}
```

**Comment by svenluijten** [comment]
@kobus1998 travis is failing because Composer is looking for `Lib`, you named your folder `lib`. Since most OS'es (🙄 looking at you, Windows...) are case sensitive, it needs to be renamed to `Lib` 🙂

**Comment by kobus1998** [comment]
@svenluijten Alright, I'm on it.

**Comment by svenluijten** [comment]
No need to close the PR! You can push new commits to the branch and they'll be added automatically ✨

**Comment by svenluijten** [comment]
heh, looks like ca7702b is "undoing" your changes. Try this:

```bash
$ git pull upstream master
# hernoem de map naar `Lib`

$ git add .
$ git commit -m "uppercase Lib folder name"
$ git push origin master --rebase
```

**Comment by kobus1998** [comment]
Renaming a file and pushing to git - episode 99 / 100

**Comment by svenluijten** [comment]
haha, we're almost there 🚀

**Comment by Feddman** [comment]
I don't even need that folder. Thought I had deleted it in the composer.json.

**Pull request closed without merging**
